name: Automatic tests, code-coverage and auto-deployment files upload to S3
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Run unit tests
        run: |
          cd ./src
          go test -race -coverprofile=../code_coverage.txt -covermode=atomic
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Code-coverage
        run: |
          cat code_coverage.txt
